---
kind: pipeline
name: default
platform:
  os: linux
  arch: arm64
  
steps:
- name: backend
  image: golang:1.13-alpine
  environment:
    USERNAME:
      from_secret: username
  commands:
  - go build
  - go test
  - echo $USERNAME
  - echo $USERNAME > a.txt
  - cat a.txt
